// This file is auto-generated by Supabase CLI
// To regenerate: npm run types
//
// Note: This is a minimal type definition to prevent build errors.
// For complete type definitions, run: npx supabase gen types typescript --local > lib/types/supabase.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      poster_boards: {
        Row: {
          id: string;
          name: string;
          lat: number;
          long: number;
          prefecture: string;
          status: Database["public"]["Enums"]["poster_board_status"];
          number: string | null;
          address: string;
          city: string;
          created_at: string;
          updated_at: string;
          row_number?: number | null;
          file_name?: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          lat: number;
          long: number;
          prefecture: string;
          status?: Database["public"]["Enums"]["poster_board_status"];
          number?: string | null;
          address: string;
          city: string;
          created_at?: string;
          updated_at?: string;
          row_number?: number | null;
          file_name?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          lat?: number;
          long?: number;
          prefecture?: string;
          status?: Database["public"]["Enums"]["poster_board_status"];
          number?: string | null;
          address?: string;
          city?: string;
          created_at?: string;
          updated_at?: string;
          row_number?: number | null;
          file_name?: string | null;
        };
      };
      poster_board_totals: {
        Row: {
          id?: string;
          prefecture?: string;
          total?: number;
          not_yet?: number;
          reserved?: number;
          done?: number;
          error_wrong_place?: number;
          error_damaged?: number;
          error_wrong_poster?: number;
          other?: number;
        };
        Insert: {
          id?: string;
          prefecture?: string;
          total?: number;
          not_yet?: number;
          reserved?: number;
          done?: number;
          error_wrong_place?: number;
          error_damaged?: number;
          error_wrong_poster?: number;
          other?: number;
        };
        Update: {
          id?: string;
          prefecture?: string;
          total?: number;
          not_yet?: number;
          reserved?: number;
          done?: number;
          error_wrong_place?: number;
          error_damaged?: number;
          error_wrong_poster?: number;
          other?: number;
        };
      };
      poster_board_status_history: {
        Row: {
          id: string;
          board_id: string;
          user_id: string;
          previous_status:
            | Database["public"]["Enums"]["poster_board_status"]
            | null;
          new_status: Database["public"]["Enums"]["poster_board_status"];
          note: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          board_id: string;
          user_id: string;
          previous_status?:
            | Database["public"]["Enums"]["poster_board_status"]
            | null;
          new_status: Database["public"]["Enums"]["poster_board_status"];
          note?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          board_id?: string;
          user_id?: string;
          previous_status?:
            | Database["public"]["Enums"]["poster_board_status"]
            | null;
          new_status?: Database["public"]["Enums"]["poster_board_status"];
          note?: string | null;
          created_at?: string;
        };
      };
      user_levels: {
        Row: {
          user_id: string;
          xp: number;
          level: number;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          xp?: number;
          level?: number;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          xp?: number;
          level?: number;
          updated_at?: string;
        };
      };
      xp_transactions: {
        Row: {
          id: string;
          user_id: string;
          xp_amount: number;
          source_type: string;
          source_id: string | null;
          description: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          xp_amount: number;
          source_type: string;
          source_id?: string | null;
          description?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          xp_amount?: number;
          source_type?: string;
          source_id?: string | null;
          description?: string | null;
          created_at?: string;
        };
      };
      mission_artifacts: {
        Row: {
          id: string;
          user_mission_id: string;
          artifact_type: string;
          artifact_url: string | null;
          created_at: string;
          updated_at: string;
          [key: string]: unknown;
        };
        Insert: {
          id?: string;
          user_mission_id: string;
          artifact_type: string;
          artifact_url?: string | null;
          created_at?: string;
          updated_at?: string;
          [key: string]: unknown;
        };
        Update: {
          id?: string;
          user_mission_id?: string;
          artifact_type?: string;
          artifact_url?: string | null;
          created_at?: string;
          updated_at?: string;
          [key: string]: unknown;
        };
      };
      missions: {
        Row: {
          id: string;
          title: string;
          icon_url: string | null;
          content: string | null;
          difficulty: number;
          event_date: string | null;
          required_artifact_type: string;
          max_achievement_count: number | null;
          created_at: string;
          updated_at: string;
          slug: string;
          ogp_image_url: string | null;
          is_featured: boolean;
          is_hidden: boolean;
          artifact_label: string | null;
          is_important: boolean;
          important_display_start_date: string | null;
          important_display_end_date: string | null;
        };
        Insert: {
          id: string;
          title: string;
          icon_url?: string | null;
          content?: string | null;
          difficulty: number;
          event_date?: string | null;
          required_artifact_type?: string;
          max_achievement_count?: number | null;
          created_at?: string;
          updated_at?: string;
          slug: string;
          ogp_image_url?: string | null;
          is_featured?: boolean;
          is_hidden?: boolean;
          artifact_label?: string | null;
          is_important?: boolean;
          important_display_start_date?: string | null;
          important_display_end_date?: string | null;
        };
        Update: {
          id?: string;
          title?: string;
          icon_url?: string | null;
          content?: string | null;
          difficulty?: number;
          event_date?: string | null;
          required_artifact_type?: string;
          max_achievement_count?: number | null;
          created_at?: string;
          updated_at?: string;
          slug?: string;
          ogp_image_url?: string | null;
          is_featured?: boolean;
          is_hidden?: boolean;
          artifact_label?: string | null;
          is_important?: boolean;
          important_display_start_date?: string | null;
          important_display_end_date?: string | null;
        };
      };
      mission_main_links: {
        Row: {
          id: string;
          mission_id: string;
          label: string;
          link: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          mission_id: string;
          label: string;
          link: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          mission_id?: string;
          label?: string;
          link?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      [key: string]: {
        Row: Record<string, unknown>;
        Insert: Record<string, unknown>;
        Update: Record<string, unknown>;
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      poster_board_status:
        | "not_yet"
        | "reserved"
        | "done"
        | "error_wrong_place"
        | "error_damaged"
        | "error_wrong_poster"
        | "other";
      [key: string]: string;
    };
  };
};

// Helper types
export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];

export type TablesInsert<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];

export type TablesUpdate<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"];
